# This file is needed to fix port issues when running the docker server on windows
# This makes sure that the backend is accessible on port 5000
services:
  skapersok:
    network_mode: bridge
    ports:
      - "5000:5000"
      - "50000:50000/udp"
